version: '3.8'

services:
  marketing-agent-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy port
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - PYTHONPATH=/app
      - DEVELOPMENT_MODE=true
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - VERBOSE_LLM=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
    env_file:
      - .env
    command: >
      sh -c "
        echo 'Starting development server...' &&
        python -m debugpy --listen 0.0.0.0:5678 --wait-for-client API/app/main.py
      "
    restart: unless-stopped
    networks:
      - marketing-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketing-net

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: marketing_agent
      POSTGRES_USER: marketing_user
      POSTGRES_PASSWORD: marketing_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketing-net

volumes:
  redis_data:
  postgres_data:

networks:
  marketing-net:
    driver: bridge
